config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins

  
  
  scope module: :users do
    root to: "homes#top"
    resources :puzzle_images, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources :comments,only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/header/_public.html.erb
<div class="col-sm-2 col-12 flex-fill">
</div>
<div class="col-sm-9 col-12">
  <ul class="d-flex flex-wrap justify-content-end">
    <li class="mt-3" style="list-style: none;"><%= link_to "新規登録",new_user_registration_path,class: "btn btn-dark flex" %></li>
    <li class="ml-2 mt-3" style="list-style: none;"><%= link_to "ログイン",new_user_session_path,class: "btn btn-dark" %></li>
    <li class="ml-2 mt-3" style="list-style: none;"><%= link_to "パズル一覧",puzzle_images_path,class: "btn btn-dark" %></li>
  </ul>
</div>

app/views/layouts/header/_user.html.erb
<div class="col-sm-3 col-12">
  <%= link_to puzzle_images_path do %>
    <%= image_tag 'puzzle_logo' ,size: "100x100" %>
  <% end %>
</div>
<div class="col-sm-9 col-12">
  <ul class="d-flex flex-wrap justify-content-end">
    <li class="mt-3" style="list-style: none;"><%= link_to "マイページ",user_path(current_user.id), class: "btn btn-dark" %></li>
    <li class="ml-2 mt-3" style="list-style: none;"><%= link_to "投稿する",new_puzzle_image_path, class: "btn btn-dark" %></li>
    <li class="ml-2 mt-3" style="list-style: none;"><%= link_to "ログアウト",destroy_user_session_path, method: :delete, class: "btn btn-dark" %></li>
  </ul>
</div>