config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins

  
  
  scope module: :users do
    root to: "homes#top"
    resources :puzzle_images, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources :comments,only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<header>
  <div class="container-fluid border-top ">
  </div>
</header>

app/views/layouts/_header.html.erb
<header>
  <div class="container-fluid">
    <div class="row">
      <nav class="navbar navbar-expand-lg navbar-light w-100">
        <div class="col-12 d-flex flex-wrap">
          <% if admin_signed_in? %>
            <%= render "layouts/header/admin"%>
          <% elsif user_signed_in? %>
            <%= render "layouts/header/user"%>
          <% else %>
            <%= render "layouts/header/public" %>
          <% end %>
        </div>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Puzzle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/5f8827088c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>